name: MegaApiClient

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Full history is required by GitVersion

      - name: Clean
        uses: cake-build/cake-action@v1
        with:
          target: Clean

      - name: Build
        uses: cake-build/cake-action@v1
        with:
          target: Pack

      - name: Doc
        uses: cake-build/cake-action@v1
        with:
          target: Doc

      - name: Test
        uses: cake-build/cake-action@v1
        with:
          target: Test
        env:
          MEGAAPICLIENT_PASSWORD: ${{ secrets.MEGAAPICLIENT_PASSWORD }}

      - name: Upload NuGet packages
        uses: actions/upload-artifact@v2
        with:
          name: NuGet packages
          path: artifacts/**/*.nupkg

      - name: Upload Documentation archive
        uses: actions/upload-artifact@v2
        with:
          name: Documentation archive
          path: artifacts/docfx.zip