name: MegaApiClient CI

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      artifactsDirectory: './artifacts/'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Full history is required by GitVersion

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          updateAssemblyInfo: true
          updateAssemblyInfoFilename: './GlobalAssemblyInfo.cs'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Create NuGet package
        run: dotnet pack --configuration Release --no-restore --no-build --output ${{ env.artifactsDirectory }} -p:PackageVersion=${{ env.GitVersion_NuGetVersionV2 }}
        if: ${{ startsWith(github.ref, 'refs/tags/v') == false }}

      - name: Create NuGet package with symbols
        run: dotnet pack --configuration Release --no-restore --no-build --output ${{ env.artifactsDirectory }} --include-symbols -p:PackageVersion=${{ env.GitVersion_NuGetVersionV2 }}
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Upload NuGet packages
        uses: actions/upload-artifact@v2
        with:
          name: NuGet packages
          path: ${{ env.artifactsDirectory }}**/*.nupkg
          if-no-files-found: error

  doc:
    name: Documentation
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install DocFX
        run: nuget install docfx.console -Version 2.56.7

      - name: Build documentation
        run: |
          ./docfx.console.2.56.7/tools/docfx.exe metadata ./docs/docfx.json
          ./docfx.console.2.56.7/tools/docfx.exe build ./docs/docfx.json
          
      - name: Upload Documentation archive
        uses: actions/upload-artifact@v2
        with:
          name: Documentation archive
          path: ./docs/_site/
          if-no-files-found: error