name: MegaApiClient CI

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build/Test
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Full history is required by GitVersion

      - name: Clean
        uses: cake-build/cake-action@v1
        with:
          target: Clean

      - name: Build
        uses: cake-build/cake-action@v1
        with:
          target: Pack

      - name: Upload NuGet packages
        uses: actions/upload-artifact@v2
        with:
          name: NuGet packages
          path: artifacts/**/*.nupkg
          if-no-files-found: error

  doc:
    name: Documentation
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      #- name: Install NuGet
      #  uses: nuget/setup-nuget@v1

      - name: Install DocFX
        run: nuget install docfx.console -Version 2.56.7

      - name: Build documentation
        run: |
          ./docfx.console.2.56.7/tools/docfx.exe metadata ./docs/docfx.json
          ./docfx.console.2.56.7/tools/docfx.exe build ./docs/docfx.json
          
      - name: Upload Documentation archive
        uses: actions/upload-artifact@v2
        with:
          name: Documentation archive
          path: ./docs/_site/
          if-no-files-found: error