name: MegaApiClient CI

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CONFIGURATION: Release

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Full history is required by GitVersion

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          updateAssemblyInfo: true
          updateAssemblyInfoFilename: './GlobalAssemblyInfo.cs'

      - name: Build
        run: dotnet build --configuration ${{ env.CONFIGURATION }}

      - name: Create NuGet package
        run: dotnet pack --configuration ${{ env.CONFIGURATION }} --no-restore --no-build --output ./artifacts/ -p:PackageVersion=${{ env.GITVERSION_NUGETVERSION }} --include-symbols

      - name: Upload NuGet packages
        uses: actions/upload-artifact@v2
        with:
          name: NuGet packages
          path: ./artifacts/*.nupkg
          if-no-files-found: error

  test:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Display files
        run: ls -R
        working-directory: ./

      - name: Tests
        run: dotnet test --configuration ${{ env.CONFIGURATION }} ./MegaApiClient.Tests/ --framework net46 --logger "console;verbosity=detailed" -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
        env:
          MEGAAPICLIENT_PASSWORD: ${{ secrets.MEGAAPICLIENT_PASSWORD }}

      - name: Display files
        run: ls -R
        working-directory: ./

  doc:
    name: Documentation
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install DocFX
        run: nuget install docfx.console -Version 2.56.7

      - name: Build documentation
        run: |
          ./docfx.console.2.56.7/tools/docfx.exe metadata ./docs/docfx.json
          ./docfx.console.2.56.7/tools/docfx.exe build ./docs/docfx.json
          
      - name: Upload Documentation archive
        uses: actions/upload-artifact@v2
        with:
          name: Documentation archive
          path: ./docs/_site/
          if-no-files-found: error